name: Hello world demo

on:
  push: # Event
    branches:
      - dev
#JOB
jobs: 
  # Print hello world
  print:
    runs-on: ubuntu-latest # Runner
    steps:
      - name: print text
        run: | # Multiline scripts for step
          echo "Hello world..!",
          echo "This is sample workflow file for dev branch"