name: CI/CD for TEST DEMO

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  # Build Job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install dependencies
        run: |
          npm install
          echo "🎉 Dependency installed successfully.."

      - name: Build and Export Project
        run: |
          npm run build
          echo "🎉 Build succeeded.."

      - name: Upload artifact for pages deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  # Deploy Job
  deploy:
    needs: build
    # We use a separate Github 'environment' called 'github-pages' to
    # handle the manual approval step. This allows us to have
    # approval gate for PROD deployment.
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    permissions:
      contents: read
      pages: write
      id-token: write

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
