name: CI/CD for TEST DEMO

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  # Build Job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install dependencies
        run: npm install

      - name: Build and Export Project
        run: npm run build

      - name: Check build output
        run: ls -la # Debugging step

      - name: Debug .next existence
        run: ls -la .next  # Check if .next exists

      - name: Upload artifact to enable deployment
        uses: actions/upload-artifact@v4
        with:
          name: production-file
          path: ./out

  # Deploy Job
  deploy:
    needs: build

    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: production-file
          path: ./out

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
